server:
  port: 8081

spring:
  application:
    name: patient-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

message: Patient service config from Config Server
